stages:
  preprocess:
    cmd: python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - data/raw/titanic.csv
    outs:
      - data/processed/titanic.csv

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/processed/titanic.csv
    outs:
      - models/best_model.pkl
    metrics:
      - metrics.json
